# Site settings
title: asmalldev
email: asmalldev@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Austin Small's personal site. Welcome!
baseurl: "/asmalldev.github.io" # the subpath of your site, e.g. /blog/
url: "/asmalldev.github.io/asmalldev.github.io" # the base hostname & protocol for your site
twitter_username: asmalldev
github_username:  asmalldev

# Build settings
markdown: kramdown
