# Site settings
title: asmalldev
email: asmalldev@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Austin Small's personal site. Welcome!
baseurl: "" # subpath
url: https://asmalldev.me
enforce_ssl: asmalldev.me
twitter_username: asmalldev
github_username:  asmalldev

# Build settings
markdown: kramdown
permalink: pretty
